import {
	PUBLIC_BACKEND_URL,
	PUBLIC_GITHUB_APPS_CLIENT_ID,
	PUBLIC_DATABASE_REPOSITORY_OWNER,
	PUBLIC_DATABASE_REPOSITORY_NAME,
	PUBLIC_DATABASE_REPOSITORY_BRANCH,
	PUBLIC_DATABASE_REPOSITORY_ACCESS_TOKEN,
	PUBLIC_DATABASE_REPOSITORY_PATH,
	PUBLIC_DATABASE_REPOSITORY_COMMITTER_NAME,
	PUBLIC_DATABASE_REPOSITORY_COMMITTER_EMAIL,
	PUBLIC_DATABASE_REPOSITORY_COMMIT_MESSAGE,
	PUBLIC_GISCUS_REPO,
	PUBLIC_GISCUS_REPO_ID,
	PUBLIC_GISCUS_CATEGORY,
	PUBLIC_GISCUS_CATEGORY_ID
} from '$env/static/public';

export const BACKEND_URL = PUBLIC_BACKEND_URL;
export const GITHUB_APPS_CLIENT_ID = PUBLIC_GITHUB_APPS_CLIENT_ID;
export const DATABASE_REPOSITORY_OWNER = PUBLIC_DATABASE_REPOSITORY_OWNER;
export const DATABASE_REPOSITORY_NAME = PUBLIC_DATABASE_REPOSITORY_NAME;
export const DATABASE_REPOSITORY_BRANCH = PUBLIC_DATABASE_REPOSITORY_BRANCH;
export const DATABASE_REPOSITORY_ACCESS_TOKEN = PUBLIC_DATABASE_REPOSITORY_ACCESS_TOKEN;
export const DATABASE_REPOSITORY_PATH = PUBLIC_DATABASE_REPOSITORY_PATH;
export const DATABASE_REPOSITORY_COMMITTER_NAME = PUBLIC_DATABASE_REPOSITORY_COMMITTER_NAME;
export const DATABASE_REPOSITORY_COMMITTER_EMAIL = PUBLIC_DATABASE_REPOSITORY_COMMITTER_EMAIL;
export const DATABASE_REPOSITORY_COMMIT_MESSAGE = PUBLIC_DATABASE_REPOSITORY_COMMIT_MESSAGE;
export const GISCUS_REPO = PUBLIC_GISCUS_REPO;
export const GISCUS_REPO_ID = PUBLIC_GISCUS_REPO_ID;
export const GISCUS_CATEGORY = PUBLIC_GISCUS_CATEGORY;
export const GISCUS_CATEGORY_ID = PUBLIC_GISCUS_CATEGORY_ID;
