export const DATABASE_REPOSITORY_OWNER = '';
export const DATABASE_REPOSITORY_NAME = '';
export const DATABASE_REPOSITORY_BRANCH = '';
export const DATABASE_REPOSITORY_ACCESS_TOKEN = '';
export const DATABASE_REPOSITORY_PATH = '';
export const DATABASE_REPOSITORY_COMMITTER_NAME = '';
export const DATABASE_REPOSITORY_COMMITTER_EMAIL = '';
export const DATABASE_REPOSITORY_COMMIT_MESSAGE = '';
