name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.5.9
          bun-config: '{"install": {"production": false}}' # You may need to write true if necessary.
          cache: true
          cache-bin: true

      - uses: actions/cache@v3
        id: bun-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      - run: bun install
        if: ${{ steps.bun-cache.outputs.cache-hit != 'true' }}

      - name: build
        run: |
          bun run build
          touch .svelte-kit/output/client/.nojekyll
          cp .svelte-kit/output/prerendered/pages/index.html .svelte-kit/output/client/
        env:
          PUBLIC_DATABASE_REPOSITORY_OWNER: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_OWNER }}
          PUBLIC_DATABASE_REPOSITORY_NAME: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_NAME }}
          PUBLIC_DATABASE_REPOSITORY_BRANCH: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_BRANCH }}
          PUBLIC_DATABASE_REPOSITORY_ACCESS_TOKEN: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_ACCESS_TOKEN }}
          PUBLIC_DATABASE_REPOSITORY_PATH: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_PATH }}
          PUBLIC_DATABASE_REPOSITORY_COMMITTER_NAME: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_COMMITTER_NAME }}
          PUBLIC_DATABASE_REPOSITORY_COMMITTER_EMAIL: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_COMMITTER_EMAIL }}
          PUBLIC_DATABASE_REPOSITORY_COMMIT_MESSAGE: ${{ secrets.PUBLIC_DATABASE_REPOSITORY_COMMIT_MESSAGE }}
          PUBLIC_GISCUS_REPO: ${{ secrets.PUBLIC_GISCUS_REPO }}
          PUBLIC_GISCUS_REPO_ID: ${{ secrets.PUBLIC_GISCUS_REPO_ID }}
          PUBLIC_GISCUS_CATEGORY: ${{ secrets.PUBLIC_GISCUS_CATEGORY }}
          PUBLIC_GISCUS_CATEGORY_ID: ${{ secrets.PUBLIC_GISCUS_CATEGORY_ID }}

      - name: Push gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # branch name
          folder: .svelte-kit/output/client
          clean: true
